name: Pros Build

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

concurrency:
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PROS Build
        uses: Lemlib/pros-build@v1
        with:
          library-path: lemlib
