name: Pros Build
on:
  push:
    branches: "main"
concurrency:
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test With Upload + Bonus Files
        uses: Lemlib/pros-build@main
        with:
          library-path: lemlib
