name: Build Template

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PROS Build
        uses: LemLib/pros-build@v1
        with:
          library-path: lemlib
